<?php
/**
 * Markdown export.
 *
 * Builds a single Markdown file containing the readable content of every
 * generated page, intended to be fed to an AI tool (Gemini Notebook, formerly NotebookLM) so a
 * site's contents can be queried in natural language. This is a separate
 * deliverable from the static HTML: it extracts the main content of each
 * page, strips the chrome (header/nav/footer), and concatenates everything
 * into one document with per-page headings.
 *
 * Distan does not generate structured data or invent content here — it only
 * transcribes what the pages already say into a plainer form.
 *
 * @package Distan
 */

defined( 'ABSPATH' ) || exit;

/**
 * Collect page content and write a combined Markdown file.
 */
final class Distan_Markdown {

	/**
	 * Output filename for the production-URL version.
	 */
	public const FILENAME = 'content.md';

	/**
	 * Output filename for the development-URL version (opt-in).
	 */
	public const FILENAME_LOCAL = 'content.local.md';

	/**
	 * Whether the Markdown export is enabled.
	 */
	public static function is_enabled(): bool {
		$settings = Distan::settings();
		return ! empty( $settings['export_markdown'] );
	}

	/**
	 * Whether the development-URL copy should also be written.
	 */
	public static function wants_local_copy(): bool {
		$settings = Distan::settings();
		return ! empty( $settings['export_markdown_local'] );
	}

	/**
	 * Extract one page into a Markdown section.
	 *
	 * @param string $html The raw page HTML (pre-rewrite is fine; only text is used).
	 * @param array<string, mixed> $item The queue item (path, url, type).
	 * @return array{title: string, url: string, body: string}|null Null when there is nothing usable.
	 */
	public static function extract( string $html, array $item ): ?array {
		if ( '' === trim( $html ) ) {
			return null;
		}

		// Skip archive pagination pages (/page/2/, /page/3/ ...). Their content
		// is just repeated post excerpts already captured on the individual
		// pages, so including them would duplicate text in the AI export.
		$url = isset( $item['url'] ) ? (string) $item['url'] : '';
		if ( '' !== $url && preg_match( '#/page/\d+/?($|\?)#', $url ) ) {
			return null;
		}

		$title = self::extract_title( $html );
		$body  = self::extract_body( $html );

		if ( '' === trim( $body ) ) {
			return null;
		}

		return array(
			'title' => $title,
			'url'   => isset( $item['url'] ) ? (string) $item['url'] : '',
			'body'  => $body,
		);
	}

	/**
	 * Append one extracted page to the Markdown export, writing the document
	 * header first on the opening call.
	 *
	 * The export is streamed one page at a time instead of concatenating every
	 * page into a single string at the end. A site with a huge number of pages
	 * therefore never has to hold the whole document (several copies over) in
	 * memory, and the job transient never has to carry every page's body
	 * between batches. The resulting file is byte-for-byte identical to the
	 * old buffered build, because to_public_urls() is a plain replacement with
	 * no matches spanning section boundaries.
	 *
	 * @param array{title: string, url: string, body: string} $section  One extracted page.
	 * @param bool                                             $is_first True for the first section of a run: the file is truncated and the header is written before the section, so a re-run never appends onto a previous run's file.
	 * @return bool True when the section reached disk.
	 */
	public static function append_section( array $section, bool $is_first ): bool {
		$block = self::render_section( $section );

		// The blocks carry development URLs (as the pages rendered them). The
		// delivered content.md swaps them for production URLs; the optional
		// content.local.md keeps the development URLs for the data owner.
		if ( $is_first ) {
			$opening = self::render_header() . $block;

			$public_ok = Distan_Paths::write( self::FILENAME, Distan_Urls::to_public_urls( $opening ) );

			if ( self::wants_local_copy() ) {
				Distan_Paths::write( self::FILENAME_LOCAL, $opening );
			}

			return $public_ok;
		}

		$public_ok = Distan_Paths::append( self::FILENAME, Distan_Urls::to_public_urls( $block ) );

		if ( self::wants_local_copy() ) {
			Distan_Paths::append( self::FILENAME_LOCAL, $block );
		}

		return $public_ok;
	}

	/**
	 * The document header: site name, optional description, and a generated
	 * marker. Written once, before the first section.
	 */
	private static function render_header(): string {
		$site_name = wp_strip_all_tags( (string) get_bloginfo( 'name' ) );
		$site_desc = wp_strip_all_tags( (string) get_bloginfo( 'description' ) );

		$lines   = array();
		$lines[] = '# ' . ( '' !== $site_name ? $site_name : 'Site' );
		if ( '' !== $site_desc ) {
			$lines[] = '';
			$lines[] = $site_desc;
		}
		$lines[] = '';
		$lines[] = sprintf(
			/* translators: %s: generation date */
			'<!-- Generated by Distan on %s -->',
			gmdate( 'Y-m-d' )
		);
		$lines[] = '';

		return implode( "\n", $lines ) . "\n";
	}

	/**
	 * Render one extracted page as its Markdown block: a divider, the heading,
	 * an optional URL line, the body, and the trailing blank line that
	 * separates it from the next section.
	 *
	 * @param array{title: string, url: string, body: string} $section One extracted page.
	 */
	private static function render_section( array $section ): string {
		$heading = '' !== $section['title'] ? $section['title'] : $section['url'];

		$lines   = array();
		$lines[] = '---';
		$lines[] = '';
		$lines[] = '## ' . $heading;
		if ( '' !== $section['url'] ) {
			$lines[] = '';
			$lines[] = 'URL: ' . $section['url'];
		}
		$lines[] = '';
		$lines[] = $section['body'];
		$lines[] = '';

		return implode( "\n", $lines ) . "\n";
	}

	/**
	 * Pull the <title>, trimming a trailing site-name suffix if present.
	 */
	private static function extract_title( string $html ): string {
		if ( preg_match( '#<title[^>]*>(.*?)</title>#is', $html, $m ) ) {
			$title = self::decode( wp_strip_all_tags( $m[1] ) );

			// Trim a common "Page Title - Site Name" / "Page Title | Site Name" suffix.
			$title = (string) preg_replace( '#\s*[\|\-–—]\s*[^\|\-–—]+$#u', '', $title );

			return trim( $title );
		}

		return '';
	}

	/**
	 * Extract the main content region and convert it to Markdown text.
	 *
	 * Prefers <main>, then <article>, then a #content / .content container,
	 * then falls back to <body>. Header, nav, footer, aside, script, style,
	 * and template noise are removed so the same chrome is not repeated on
	 * every page.
	 */
	private static function extract_body( string $html ): string {
		$region = self::isolate_region( $html );

		// Remove non-content elements wholesale.
		$strip_blocks = array( 'script', 'style', 'noscript', 'template', 'svg', 'header', 'footer', 'nav', 'aside', 'form' );
		foreach ( $strip_blocks as $tag ) {
			$region = (string) preg_replace( '#<' . $tag . '\b[^>]*>.*?</' . $tag . '>#is', '', $region );
		}

		// Allow filtering the content region before conversion (theme-specific cleanup).
		$region = (string) apply_filters( 'distan_markdown_region', $region );

		return self::html_to_markdown( $region );
	}

	/**
	 * Narrow the HTML down to the most likely content region.
	 */
	private static function isolate_region( string $html ): string {
		// Allow a theme to declare the content selector's tag/class via filter,
		// but default to a sensible priority list.
		if ( preg_match( '#<main\b[^>]*>(.*?)</main>#is', $html, $m ) ) {
			return $m[1];
		}

		if ( preg_match( '#<article\b[^>]*>(.*?)</article>#is', $html, $m ) ) {
			return $m[1];
		}

		if ( preg_match( '#<div\b[^>]*(?:id|class)=["\'][^"\']*\bcontent\b[^"\']*["\'][^>]*>(.*?)</div>\s*(?:</div>)*#is', $html, $m ) ) {
			return $m[1];
		}

		if ( preg_match( '#<body\b[^>]*>(.*?)</body>#is', $html, $m ) ) {
			return $m[1];
		}

		return $html;
	}

	/**
	 * Convert a fragment of HTML to a plain Markdown-ish text.
	 *
	 * Deliberately small and dependency-free: headings, paragraphs, list
	 * items, links, and line breaks. The goal is readable text for an AI to
	 * ingest, not a perfect Markdown round-trip.
	 */
	private static function html_to_markdown( string $html ): string {
		$text = $html;

		// Headings h1-h6 -> Markdown headings.
		for ( $level = 1; $level <= 6; $level++ ) {
			$text = (string) preg_replace_callback(
				'#<h' . $level . '\b[^>]*>(.*?)</h' . $level . '>#is',
				static function ( $m ) use ( $level ) {
					$inner = trim( wp_strip_all_tags( $m[1] ) );
					return '' !== $inner ? "\n\n" . str_repeat( '#', $level ) . ' ' . $inner . "\n\n" : '';
				},
				$text
			);
		}

		// Links -> [text](href). Do this before stripping tags.
		$text = (string) preg_replace_callback(
			'#<a\b[^>]*href=["\']([^"\']*)["\'][^>]*>(.*?)</a>#is',
			static function ( $m ) {
				$label = trim( wp_strip_all_tags( $m[2] ) );
				$href  = trim( $m[1] );
				if ( '' === $label ) {
					return '';
				}
				if ( '' === $href || str_starts_with( $href, '#' ) ) {
					return $label;
				}
				return '[' . $label . '](' . $href . ')';
			},
			$text
		);

		// List items -> "- ...".
		$text = (string) preg_replace_callback(
			'#<li\b[^>]*>(.*?)</li>#is',
			static function ( $m ) {
				$inner = trim( wp_strip_all_tags( $m[1] ) );
				return '' !== $inner ? "\n- " . $inner : '';
			},
			$text
		);

		// Paragraphs and breaks -> newlines.
		$text = (string) preg_replace( '#</p>#i', "\n\n", $text );
		$text = (string) preg_replace( '#<br\s*/?>#i', "\n", $text );

		// Block boundaries -> newline, so words do not run together.
		$text = (string) preg_replace( '#</(div|section|tr|thead|tbody|table|ul|ol|h[1-6])>#i', "\n", $text );

		// Strip everything else.
		$text = wp_strip_all_tags( $text );
		$text = self::decode( $text );

		// Collapse whitespace: trim each line, cap blank runs at one.
		$lines = preg_split( '#\R#u', $text ) ?: array();
		$out   = array();
		$blank = 0;
		foreach ( $lines as $line ) {
			$line = trim( (string) $line );
			if ( '' === $line ) {
				$blank++;
				if ( $blank <= 1 ) {
					$out[] = '';
				}
				continue;
			}
			$blank = 0;
			$out[] = $line;
		}

		return trim( implode( "\n", $out ) );
	}

	/**
	 * Decode HTML entities to their characters.
	 */
	private static function decode( string $text ): string {
		return html_entity_decode( $text, ENT_QUOTES | ENT_HTML5, 'UTF-8' );
	}
}
